# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: shiny-deploy

on:
  push:
    branches:
      - IT-828
      - master
      - release*

jobs:
  shiny-deploy:
    runs-on: ubuntu-latest
     env:
      # This should not be necessary for installing from public repo's however install_github() fails without it.
      GITHUB_PAT: ${{ secrets.REPO_PAT }}
 
    steps:
 
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
 
      - uses: actions/checkout@v2

      - name: Install R packages
        run: |
          # The binary package distributions from R Studio dramatically speed up installation time
          # For Ubuntu 18.04 (Bionic) it's https://packagemanager.rstudio.com/all/__linux__/bionic/latest
          # For Ubuntu 20.04 (Focal)  it's https://packagemanager.rstudio.com/all/__linux__/focal/latest 
          options(repos = c(REPO_NAME = "https://packagemanager.rstudio.com/all/__linux__/bionic/latest", getOption("repos")))
          install.packages(c("rsconnect", "devtools"))
          devtools::install_github("Sage-Bionetworks/projectlive.modules")
        shell: Rscript {0}

      - name: Authorize and deploy app
        run: |
          branch<-Sys.getenv("GITHUB_REF_NAME")
          repo<-Sys.getenv("GITHUB_REPOSITORY")
          appName<-strsplit(repo, "/")[[1]][2]
          if (!startsWith(branch, "release")) {
             appName = paste(appName, "staging", sep="-")
          }
          rsconnect::setAccountInfo("${{ secrets.RSCONNECT_USER }}", "${{ secrets.RSCONNECT_TOKEN }}", "${{ secrets.RSCONNECT_SECRET }}")
          rsconnect::deployApp(appName = appName)
        shell: Rscript {0}
